services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
  
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./Backend/app:/app/app
      - ./Backend/.env:/app/.env
    depends_on:
      - mongo-express
      - mongodb

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - node_modules:/app/node_modules # Evita el problema de node_modules

volumes:
  mongo-data:
    driver: local
  node_modules: # Agrego volumen nombrado para node_modules del frontend
