services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend/app:/app/app
       - ./Backend/.env:/app/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
    driver: local

